[linux_audit]
FIELDALIAS-process_name = comm AS process_name
FIELDALIAS-command_line = cmd AS command_line
FIELDALIAS-executable = exe AS executable
FIELDALIAS-process_id = pid AS process_id
FIELDALIAS-parent_process_id = ppid AS parent_process_id
FIELDALIAS-hostname = host AS hostname

[linux_auth]
FIELDALIAS-user = USER AS user
FIELDALIAS-tty = TTY AS tty
FIELDALIAS-command_line = COMMAND AS command_line
FIELDALIAS-cwd = CWD AS cwd
FIELDALIAS-hostname = host AS hostname

[sudo]
REPORT-linux_sudo_user = linux_sudo_user
REPORT-linux_sudo_pwd = linux_sudo_pwd
REPORT-linux_sudo_command_line = linux_sudo_command_line
FIELDALIAS-hostname = host AS hostname

[sshd]
REPORT-linux_sshd_fields = linux_sshd_fields
FIELDALIAS-hostname = host AS hostname

[bash_history]
REPORT-linux_bash_history_fields = linux_bash_history_fields
FIELDALIAS-hostname = host AS hostname

[syslog]
REPORT-syslog-user = syslog-user
REPORT-syslog-pwd = syslog-pwd
REPORT-syslog-cmd = syslog-cmd
REPORT-syslog-cmd-2 = syslog-cmd-2
FIELDALIAS-process_name = process AS process_name
FIELDALIAS-process_id = pid AS process_id
FIELDALIAS-hostname = host AS hostname

[yara]
REPORT-yara_fields = yara_fields
FIELDALIAS-hostname-linux = host AS hostname

[YARA]
REPORT-yara_fields = yara_fields
FIELDALIAS-hostname-windows = ComputerName AS hostname


[WinEventLog:Security]
FIELDALIAS-event_code = EventCode  AS event_code
FIELDALIAS-process_name = Nom_du_processus  AS process_name
FIELDALIAS-hostname = ComputerName AS hostname
FIELDALIAS-action = TaskCategory AS action
FIELDALIAS-type = Type_d_ouverture_de_session AS logon_type

[WinEventLog:Microsoft-Windows-Sysmon/Operational]
FIELDALIAS-command_line = CommandLine AS command_line
FIELDALIAS-hostname = ComputerName AS hostname
FIELDALIAS-event_code = EventCode  AS event_code
FIELDALIAS-hashes = Hashes AS hashes
FIELDALIAS-executable = Image AS executable
FIELDALIAS-parent_executable = ParentImage AS parent_executable
FIELDALIAS-process_id = ProcessId AS process_id
FIELDALIAS-parent_process_id = ParentProcessId AS parent_process_id
FIELDALIAS-message = Message AS message
FIELDALIAS-parent_command_line = ParentCommandLine AS parent_command_line
FIELDALIAS-user = User AS user

[WinEventLog:Microsoft-Windows-PowerShell/Operational]
FIELDALIAS-hostname = ComputerName AS hostname
FIELDALIAS-event_code = EventCode  AS event_code
FIELDALIAS-message = Message AS message
FIELDALIAS-user = User AS user

[WinEventLog:System]
FIELDALIAS-hostname = ComputerName AS hostname
FIELDALIAS-event_code = EventCode  AS event_code
FIELDALIAS-message = Message AS message
FIELDALIAS-user = User AS user
FIELDALIAS-type = Type AS type
FIELDALIAS-src_name = SourceName AS src_name

[suricata]
FIELDALIAS-protocol = proto AS protocol
FIELDALIAS-alert_signature  = alert.signature AS alert_signature
FIELDALIAS-alert_severity  = alert.severity AS alert_severity
FIELDALIAS-alert_action  = alert.signature AS alert_action

[zeek_conn]
REPORT-zeek_conn = zeek_conn

[zeek_dns]
REPORT-zeek_dns = zeek_dns

[stash]
REPORT-alert_name = alert_name

[stash]
REPORT-alert_rule_id = alert_rule_id

[stash]
REPORT-alert_mitre_technique = alert_mitre_technique

[stash]
REPORT-alert_severity = alert_severity

[stash]
REPORT-alert_sigma_id = alert_sigma_id

[stash]
REPORT-alert_platform = alert_platform

[stash]
REPORT-alert_datasource = alert_datasource

[stash]
REPORT-alert_time = alert_time

[stash]
REPORT-alert_formatted_time = alert_formatted_time
