[linux_sudo_user]
REGEX = USER=(?<user>\S+)

[linux_sudo_pwd]
REGEX = PWD=(?<pwd>\S+)

[linux_sudo_command_line]
REGEX = COMMAND=(?<command_line>.*)

[linux_sshd_fields]
REGEX = sshd\[(?<process_id>\d+)\]: (?<authentication_action>.+) for (?<user>\S+) from (?<src_ip>\S+) port (?<src_port>\d+) (?<protocol>\S+)

[linux_bash_history_fields]
REGEX = USER=(?<user>\S+)\sPWD=(?<pwd>\S+)\sCMD=#011 (?<command_line>.*)

[yara_fields]
REGEX = (?ms)(?:.*^Message=)?(?<alert_signature>\S+)\s(?<file_path>\S.*)

[syslog-user]
REGEX = USER=(?<user>\S+)

[syslog-pwd]
REGEX = PWD=(?<pwd>\S+)

[syslog-cmd]
REGEX = (?=.*CMD=)CMD=#011 (?<command_line>.*)

[syslog-cmd-2]
REGEX = (?=.*CMD )CMD (?<command_line>.*)

[zeek_conn]
REGEX = (?<ts>[^\t]+)\t(?<uid>[^\t]+)\t(?<src_ip>[^\t]+)\t(?<src_port>[^\t]+)\t(?<dest_ip>[^\t]+)\t(?<dest_port>[^\t]+)\t(?<protocol>[^\t]+)

[zeek_dns]
REGEX = (?<ts>[^\t]+)\t(?<uid>[^\t]+)\t(?<src_ip>[^\t]+)\t(?<src_port>[^\t]+)\t(?<dest_ip>[^\t]+)\t(?<dest_port>[^\t]+)\t(?<protocol>[^\t]+)

[alert_name]
REGEX = alert_name=\"(?<alert_name>[^\"]+)\"*

[alert_rule_id]
REGEX = rule_id=\"(?<rule_id>[^\"]+)\"

[alert_mitre_technique]
REGEX = mitre_technique=\"(?<mitre_technique>[^\"]+)\"

[alert_severity]
REGEX = severity=\"(?<severity>[^\"]+)\"

[alert_sigma_id]
REGEX = sigma_id=\"(?<sigma_id>[^\"]+)\"

[alert_platform]
REGEX = platform=\"(?<platform>[^\"]+)\"

[alert_datasource]
REGEX = datasource=\"(?<datasource>[^\"]+)\"

[alert_time]
REGEX = time=\"(?<time>[^\"]+)\"

[alert_formatted_time]
REGEX = formatted_time=\"(?<formatted_time>[^\"]+)\"
